opentelemetry:
  grpc:
    enabled: true # takes precedence over legacy settings above, defaults to true iff "grpc:" is present
  http:
    enabled: true # allows to enable http endpoints, defaults to true iff "http:" is present

agent:
  configuration_yaml: |
    com.instana.plugin.prometheus:
      poll_rate: 5 
      customMetricSources:
      - url: '/'  
        metricNameIncludeRegex: '.*' 

    # otel-demo configurations
    com.instana.plugin.postgresql:
      user: 'ffs'
      password: 'ffs'
      database: 'postgres'
